note=mfront

all:
	latex  $(note).tex
	latex  $(note).tex
	bibtex $(note)
	latex  $(note).tex
	latex  $(note).tex
	dvips  $(note).dvi -o
	ps2pdf $(note).ps

clean:
	-$(RM) $(note).aux $(note).log
	-$(RM) $(note).out $(note).toc
	-$(RM) $(note).dvi $(note).ps
	-$(RM) $(note).pdf
