      FUNCTION COMPUTEYOUNG(T)
      IMPLICIT NONE
      DOUBLE PRECISION COMPUTEYOUNG
      DOUBLE PRECISION T
      DOUBLE PRECISION VANADIUMALLOY_YOUNGMODULUS_SRMA
      T = 900.D0
      COMPUTEYOUNG = VANADIUMALLOY_YOUNGMODULUS_SRMA(T)
      END

      FUNCTION COMPUTENU(T)
      IMPLICIT NONE
      DOUBLE PRECISION COMPUTENU
      DOUBLE PRECISION T
      DOUBLE PRECISION VANADIUMALLOY_POISSONRATIO_SRMA
      T = 900.D0
      COMPUTENU = VANADIUMALLOY_POISSONRATIO_SRMA(T)
      END
