AC_DEFUN([CHECK_CYRANO_MACHINE_TYPE],[
    AC_REQUIRE([AC_CANONICAL_HOST])dnl
    AC_CHECKING("cyrano unix type")
    if test "x$TFEL_ARCH32" = "xyes" ;
    then
	CYRANO_ARCH=32
    else
	CYRANO_ARCH=64
    fi
    AC_DEFINE_UNQUOTED(CYRANO_ARCH,$CYRANO_ARCH)
])