message(STATUS "looked for castem library.")

set(CASTEMHOME $ENV{CASTEMHOME})
if(CASTEMHOME)
    find_path(CASTEM_INCLUDE_DIR castem.h
              HINTS ${CASTEMHOME}/include)
    if(CASTEM_INCLUDE_DIR STREQUAL "CASTEM_INCLUDE_DIR-NOTFOUND")
    	message(FATAL_ERROR "castem.h not found")
    endif(CASTEM_INCLUDE_DIR STREQUAL "CASTEM_INCLUDE_DIR-NOTFOUND")
    message(STATUS "Include file detected: [${CASTEM_INCLUDE_DIR}].")
    if(WIN32)
    add_definitions("-DCASTEM_CPPFLAGS=\\\"\"\"\\\"")	
    endif(WIN32)
    if(UNIX)
        if( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    	    add_definitions("-DCASTEM_CPPFLAGS=\\\"\"-DSUN -DUNIX32 -DTHREAD\"\\\"")	
    	    add_definitions("-DSUN -DUNIX32 -DTHREAD")
	    add_definitions("-DCASTEM_UNIX_TYPE=UNIX32")
	else( CMAKE_SIZEOF_VOID_P EQUAL 8 )
            add_definitions("-DCASTEM_CPPFLAGS=\\\"\"-DSUN -DUNIX64 -DTHREAD\"\\\"")
    	    add_definitions("-DSUN -DUNIX64 -DTHREAD")
	    add_definitions("-DCASTEM_UNIX_TYPE=UNIX64")
	endif( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    endif(UNIX)
    add_definitions("-DCASTEM_ROOT=\\\"\"${CASTEMHOME}\"\\\"")
    set(HAVE_CASTEM ON)
else(CASTEMHOME)
  message(WARNING "no CASTEMHOME environment defined")
endif(CASTEMHOME)

