if(WIN32)
  add_definitions("-DCASTEM_CPPFLAGS=\\\"\"\"\\\"")	
endif(WIN32)
if(UNIX)
  if( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    set(CASTEM_CPPFLAGS "-DSUN -DUNIX64 -DTHREAD")
    add_definitions("-DCASTEM_UNIX_TYPE=UNIX64")
  else( CMAKE_SIZEOF_VOID_P EQUAL 8 )
    set(CASTEM_CPPFLAGS "-DSUN -DUNIX32 -DTHREAD")
    add_definitions("-DCASTEM_UNIX_TYPE=UNIX32")
  endif( CMAKE_SIZEOF_VOID_P EQUAL 8 )
  add_definitions("-DCASTEM_CPPFLAGS=\\\"\"${CASTEM_CPPFLAGS}\"\\\"")
  add_definitions("${CASTEM_CPPFLAGS}")
endif(UNIX)
