include(cmake/modules/compiler.cmake)

tfel_enable_cxx_compiler_flag(COMPILER_WARNINGS  "Wall" "W" "Wextra" "pedantic" "Wshadow")
tfel_enable_cxx_compiler_flag(COMPILER_WARNINGS  "fvisibility-inlines-hidden")
tfel_enable_cxx_compiler_flag(COMPILER_WARNINGS  "Wpointer-arith" "Wcast-qual" "Wcast-align")
tfel_enable_cxx_compiler_flag(COMPILER_WARNINGS  "Wwrite-strings" "Wctor-dtor-privacy" "Wnon-virtual-dtor")
tfel_enable_cxx_compiler_flag(COMPILER_WARNINGS  "Woverloaded-virtual" "Wreturn-type" "Wfloat-equal")
tfel_enable_cxx_compiler_flag(COMPILER_WARNINGS  "Wno-endif-labels" "Wsign-compare" "Wmissing-format-attribute")
tfel_enable_cxx_compiler_flag(COMPILER_WARNINGS  "Wno-multichar" "Wno-deprecated-declarations" "Wpacked")
tfel_enable_cxx_compiler_flag(COMPILER_WARNINGS  "Wredundant-decls" "Wlong-long" "Wdisabled-optimization")
tfel_enable_cxx_compiler_flag(COMPILER_WARNINGS  "Wunknown-pragmas" "Wundef" "Wreorder")
tfel_enable_cxx_compiler_flag(OPTIMISATION_FLAGS "fvisibility=hidden")
tfel_enable_cxx_compiler_flag(OPTIMISATION_FLAGS "fvisibility-inlines-hidden")
tfel_enable_cxx_compiler_flag(OPTIMISATION_FLAGS "march=native")

message(STATUS "optimisation flags : ${OPTIMISATION_FLAGS}")
message(STATUS "compiler warnings  : ${COMPILER_WARNINGS}")

if(HAVE_FORTRAN)
  get_filename_component (Fortran_COMPILER_NAME ${CMAKE_Fortran_COMPILER} NAME)
  if ("${Fortran_COMPILER_NAME}" MATCHES "^gfortran.*")
    add_definitions("-D'F77_FUNC(X,Y)=X\\#\\#_' -D'F77_FUNC_(X,Y)=X\\#\\#_'")
  elseif("${Fortran_COMPILER_NAME}" MATCHES "^g77.*")
    add_definitions("-D'F77_FUNC(X,Y)=X\\#\\#_' -D'F77_FUNC_(X,Y)=X\\#\\#__'")
  else("${Fortran_COMPILER_NAME}" MATCHES "^gfortran.*")
    message(FATAL_ERROR "unsupported fortran compiler ${CMAKE_Fortran_COMPILER_NAME}")
  endif("${Fortran_COMPILER_NAME}" MATCHES "^gfortran.*")
endif(HAVE_FORTRAN)

