include(cmake/modules/compiler.cmake)
include(cmake/modules/common-compiler-flags.cmake)

tfel_enable_cxx_compiler_flag(COMPILER_WARNINGS  "Wdisabled-optimization")
tfel_enable_cxx_compiler_flag(OPTIMISATION_FLAGS "fvisibility=hidden")
tfel_enable_cxx_compiler_flag(OPTIMISATION_FLAGS "fvisibility-inlines-hidden")
tfel_enable_cxx_compiler_flag(OPTIMISATION_FLAGS "march=native")

set(OPTIMISATION_FLAGS "-DNO_RUNTIME_CHECK_BOUNDS ${OPTIMISATION_FLAGS}")

if(CMAKE_BUILD_TYPE STREQUAL "Release")
  add_definitions("-DNDEBUG")
endif(CMAKE_BUILD_TYPE STREQUAL "Release")

if(HAVE_FORTRAN)
  get_filename_component (Fortran_COMPILER_NAME ${CMAKE_Fortran_COMPILER} NAME)
  if ("${Fortran_COMPILER_NAME}" MATCHES "^gfortran.*")
    set(GNU_FORTRAN_COMPILER ON)
    add_definitions("-D'F77_FUNC(X,Y)=X\\#\\#_' -D'F77_FUNC_(X,Y)=X\\#\\#_'")
  elseif("${Fortran_COMPILER_NAME}" MATCHES "^g77.*")
    set(GNU_FORTRAN_COMPILER ON)
    add_definitions("-D'F77_FUNC(X,Y)=X\\#\\#_' -D'F77_FUNC_(X,Y)=X\\#\\#__'")
  else("${Fortran_COMPILER_NAME}" MATCHES "^gfortran.*")
    message(FATAL_ERROR "unsupported fortran compiler ${CMAKE_Fortran_COMPILER_NAME}")
  endif("${Fortran_COMPILER_NAME}" MATCHES "^gfortran.*")
endif(HAVE_FORTRAN)
