get_filename_component (Fortran_COMPILER_NAME ${CMAKE_Fortran_COMPILER} NAME)
if("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "GNU")
  set(GNU_FORTRAN_COMPILER ON)
  if(MSYS)
    add_definitions("-D'F77_FUNC(X,Y)=X##_' -D'F77_FUNC_(X,Y)=X##_'")
  else(MSYS)
    add_definitions("-D'F77_FUNC(X,Y)=X\\#\\#_' -D'F77_FUNC_(X,Y)=X\\#\\#_'")
  endif(MSYS)
else("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "GNU")
  message(FATAL_ERROR "unsupported fortran compiler ${Fortran_COMPILER_NAME}")
endif("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "GNU")