  get_filename_component (Fortran_COMPILER_NAME ${CMAKE_Fortran_COMPILER} NAME)
  if ("${Fortran_COMPILER_NAME}" MATCHES "^gfortran.*")
    set(GNU_FORTRAN_COMPILER ON)
    add_definitions("-D'F77_FUNC(X,Y)=X\\#\\#_' -D'F77_FUNC_(X,Y)=X\\#\\#_'")
  elseif("${Fortran_COMPILER_NAME}" MATCHES "^g77.*")
    set(GNU_FORTRAN_COMPILER ON)
    add_definitions("-D'F77_FUNC(X,Y)=X\\#\\#_' -D'F77_FUNC_(X,Y)=X\\#\\#__'")
  else("${Fortran_COMPILER_NAME}" MATCHES "^gfortran.*")
    message(FATAL_ERROR "unsupported fortran compiler ${CMAKE_Fortran_COMPILER_NAME}")
  endif("${Fortran_COMPILER_NAME}" MATCHES "^gfortran.*")