option(enable-random-tests "allow tests based on random rounding mode" OFF)
set(IEEE754_ROUNDING_MODES )
if(NOT TFEL_BROKEN_LIBMATH)
  list(APPEND IEEE754_ROUNDING_MODES "UpWard")
  list(APPEND IEEE754_ROUNDING_MODES "DownWard")
  list(APPEND IEEE754_ROUNDING_MODES "ToNearest")
  list(APPEND IEEE754_ROUNDING_MODES "TowardZero")
  if(enable-random-tests)
    list(APPEND IEEE754_ROUNDING_MODES "Random")
  endif(enable-random-tests)
else(NOT TFEL_BROKEN_LIBMATH)
  list(APPEND IEEE754_ROUNDING_MODES "ToNearest")
endif(NOT TFEL_BROKEN_LIBMATH)
