AC_DEFUN([CHECK_ASTER_MACHINE_TYPE],[
    AC_REQUIRE([AC_CANONICAL_HOST])dnl
    AC_CHECKING("aster unix type")
    if test "x$TFEL_ARCH32" = "xyes" ;
    then
	ASTER_ARCH=32
    else
	ASTER_ARCH=64
    fi
    AC_DEFINE_UNQUOTED(ASTER_ARCH,$ASTER_ARCH)
])