name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7
      with:
        path: tfel

    - name: Configure CMake
      run: cmake ${{github.workspace}}/tfel                           \
                 -B ${{github.workspace}}/build                       \
                 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}               \
                 -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j $(nproc)

    - name: Test
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target check -j $(nproc)
        mkdir ${{github.workspace}}/tests-results
        cp $(find ${{github.workspace}}/build -name *.xml) ${{github.workspace}}/tests-results

    - name: Print test log on failure
      if: ${{ matrix.os == 'ubuntu-latest' && failure() }}
      run: |
        cat ${{github.workspace}}/build/Testing/Temporary/LastTest.log

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v6
      if: ${{ matrix.os == 'ubuntu-latest' && (success() || failure()) }} # always run even if the previous step fails
      with:
        report_paths: '**/tests-results/*.xml'

    - name: Running tfel-check
      run: |
        source ${{github.workspace}}/install/share/tfel/env/env.sh
        cd ${{github.workspace}}/install/share/tfel/test-suite
        tfel-check
